/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PostApiRankingTeamRegistrationsRankingIdGenerateMatchesBody,
  PostApiRankingTeamRegistrationsRankingIdTeamsBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class RankingTeamsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar equipos inscritos en un ranking
 */
 getApiRankingTeamRegistrationsRankingIdTeams<TData = void>(rankingId: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiRankingTeamRegistrationsRankingIdTeams<TData = void>(rankingId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiRankingTeamRegistrationsRankingIdTeams<TData = void>(rankingId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiRankingTeamRegistrationsRankingIdTeams<TData = void>(
    rankingId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Inscribe un equipo en el ranking. Si el ranking ya cuenta con calendario generado, sincroniza y regenera automáticamente los partidos pendientes conservando los resultados ya disputados entre equipos activos.
 * @summary Inscribir un equipo en un ranking (ADMIN u ORGANIZER)
 */
 postApiRankingTeamRegistrationsRankingIdTeams<TData = void>(rankingId: string,
    postApiRankingTeamRegistrationsRankingIdTeamsBody: PostApiRankingTeamRegistrationsRankingIdTeamsBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiRankingTeamRegistrationsRankingIdTeams<TData = void>(rankingId: string,
    postApiRankingTeamRegistrationsRankingIdTeamsBody: PostApiRankingTeamRegistrationsRankingIdTeamsBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiRankingTeamRegistrationsRankingIdTeams<TData = void>(rankingId: string,
    postApiRankingTeamRegistrationsRankingIdTeamsBody: PostApiRankingTeamRegistrationsRankingIdTeamsBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiRankingTeamRegistrationsRankingIdTeams<TData = void>(
    rankingId: string,
    postApiRankingTeamRegistrationsRankingIdTeamsBody: PostApiRankingTeamRegistrationsRankingIdTeamsBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams`,
      postApiRankingTeamRegistrationsRankingIdTeamsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams`,
      postApiRankingTeamRegistrationsRankingIdTeamsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams`,
      postApiRankingTeamRegistrationsRankingIdTeamsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Da de baja a un equipo de un ranking. Elimina los partidos asociados a dicho equipo y, si quedan al menos 4 equipos activos, regenera los partidos pendientes conservando los resultados jugados entre el resto de equipos.
 * @summary Desinscribir un equipo de un ranking (ADMIN u ORGANIZER)
 */
 deleteApiRankingTeamRegistrationsRankingIdTeamsTeamId<TData = void>(rankingId: string,
    teamId: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiRankingTeamRegistrationsRankingIdTeamsTeamId<TData = void>(rankingId: string,
    teamId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiRankingTeamRegistrationsRankingIdTeamsTeamId<TData = void>(rankingId: string,
    teamId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiRankingTeamRegistrationsRankingIdTeamsTeamId<TData = void>(
    rankingId: string,
    teamId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams/${teamId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams/${teamId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/ranking-team-registrations/${rankingId}/teams/${teamId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Genera los partidos round-robin para todos los equipos inscritos activos en el ranking con soporte multivuelta. Preserva resultados disputados existentes.
 * @summary Generar calendario de partidos Round-Robin para los equipos inscritos (mínimo 4 equipos)
 */
 postApiRankingTeamRegistrationsRankingIdGenerateMatches<TData = void>(rankingId: string,
    postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody?: PostApiRankingTeamRegistrationsRankingIdGenerateMatchesBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiRankingTeamRegistrationsRankingIdGenerateMatches<TData = void>(rankingId: string,
    postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody?: PostApiRankingTeamRegistrationsRankingIdGenerateMatchesBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiRankingTeamRegistrationsRankingIdGenerateMatches<TData = void>(rankingId: string,
    postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody?: PostApiRankingTeamRegistrationsRankingIdGenerateMatchesBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiRankingTeamRegistrationsRankingIdGenerateMatches<TData = void>(
    rankingId: string,
    postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody?: PostApiRankingTeamRegistrationsRankingIdGenerateMatchesBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/ranking-team-registrations/${rankingId}/generate-matches`,
      postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/ranking-team-registrations/${rankingId}/generate-matches`,
      postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/ranking-team-registrations/${rankingId}/generate-matches`,
      postApiRankingTeamRegistrationsRankingIdGenerateMatchesBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

