/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  ForgotPasswordRequest,
  GetApiAuthProfile200,
  LoginRequest,
  LoginResponse,
  PostApiAuthForgotPassword200,
  PostApiAuthResetPassword200,
  PostApiAuthSetupPassword200,
  ResetPasswordRequest,
  SetupPasswordRequest
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly http = inject(HttpClient);
/**
 * @summary Iniciar sesión
 */
 postApiAuthLogin<TData = LoginResponse>(loginRequest: LoginRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAuthLogin<TData = LoginResponse>(loginRequest: LoginRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAuthLogin<TData = LoginResponse>(loginRequest: LoginRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAuthLogin<TData = LoginResponse>(
    loginRequest: LoginRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/login`,
      loginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/login`,
      loginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/login`,
      loginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Configurar contraseña inicial mediante token de bienvenida
 */
 postApiAuthSetupPassword<TData = PostApiAuthSetupPassword200>(setupPasswordRequest: SetupPasswordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAuthSetupPassword<TData = PostApiAuthSetupPassword200>(setupPasswordRequest: SetupPasswordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAuthSetupPassword<TData = PostApiAuthSetupPassword200>(setupPasswordRequest: SetupPasswordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAuthSetupPassword<TData = PostApiAuthSetupPassword200>(
    setupPasswordRequest: SetupPasswordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/setup-password`,
      setupPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/setup-password`,
      setupPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/setup-password`,
      setupPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Solicitar recuperación de contraseña
 */
 postApiAuthForgotPassword<TData = PostApiAuthForgotPassword200>(forgotPasswordRequest: ForgotPasswordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAuthForgotPassword<TData = PostApiAuthForgotPassword200>(forgotPasswordRequest: ForgotPasswordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAuthForgotPassword<TData = PostApiAuthForgotPassword200>(forgotPasswordRequest: ForgotPasswordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAuthForgotPassword<TData = PostApiAuthForgotPassword200>(
    forgotPasswordRequest: ForgotPasswordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/forgot-password`,
      forgotPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/forgot-password`,
      forgotPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/forgot-password`,
      forgotPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Restablecer contraseña con token de recuperación
 */
 postApiAuthResetPassword<TData = PostApiAuthResetPassword200>(resetPasswordRequest: ResetPasswordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAuthResetPassword<TData = PostApiAuthResetPassword200>(resetPasswordRequest: ResetPasswordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAuthResetPassword<TData = PostApiAuthResetPassword200>(resetPasswordRequest: ResetPasswordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAuthResetPassword<TData = PostApiAuthResetPassword200>(
    resetPasswordRequest: ResetPasswordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/reset-password`,
      resetPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/reset-password`,
      resetPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/reset-password`,
      resetPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener perfil del usuario autenticado
 */
 getApiAuthProfile<TData = GetApiAuthProfile200>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAuthProfile<TData = GetApiAuthProfile200>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAuthProfile<TData = GetApiAuthProfile200>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAuthProfile<TData = GetApiAuthProfile200>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/auth/profile`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/auth/profile`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/auth/profile`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

