/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GetApiAuthProfile200,
  LoginResponse,
  PostApiAuthForgotPassword200,
  PostApiAuthResetPassword200,
  PostApiAuthSetupPassword200
} from '../../model';

import {
  getGetApiAuthProfileResponseMock,
  getPostApiAuthForgotPasswordResponseMock,
  getPostApiAuthLoginResponseMock,
  getPostApiAuthResetPasswordResponseMock,
  getPostApiAuthSetupPasswordResponseMock
} from './auth.faker';

export { getPostApiAuthLoginResponseMock, getPostApiAuthSetupPasswordResponseMock, getPostApiAuthForgotPasswordResponseMock, getPostApiAuthResetPasswordResponseMock, getGetApiAuthProfileResponseMock } from './auth.faker';


export const getPostApiAuthLoginMockHandler = (overrideResponse?: LoginResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LoginResponse> | LoginResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAuthLoginResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiAuthSetupPasswordMockHandler = (overrideResponse?: PostApiAuthSetupPassword200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiAuthSetupPassword200> | PostApiAuthSetupPassword200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/setup-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAuthSetupPasswordResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiAuthForgotPasswordMockHandler = (overrideResponse?: PostApiAuthForgotPassword200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiAuthForgotPassword200> | PostApiAuthForgotPassword200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/forgot-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAuthForgotPasswordResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiAuthResetPasswordMockHandler = (overrideResponse?: PostApiAuthResetPassword200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiAuthResetPassword200> | PostApiAuthResetPassword200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/reset-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAuthResetPasswordResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiAuthProfileMockHandler = (overrideResponse?: GetApiAuthProfile200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiAuthProfile200> | GetApiAuthProfile200), options?: RequestHandlerOptions) => {
  return http.get('*/api/auth/profile', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiAuthProfileResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAuthMock = () => [
  getPostApiAuthLoginMockHandler(),
  getPostApiAuthSetupPasswordMockHandler(),
  getPostApiAuthForgotPasswordMockHandler(),
  getPostApiAuthResetPasswordMockHandler(),
  getGetApiAuthProfileMockHandler()]
