/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  Role
} from '../../model';
import type {
  GetApiAuthProfile200,
  LoginResponse,
  PostApiAuthForgotPassword200,
  PostApiAuthResetPassword200,
  PostApiAuthSetupPassword200
} from '../../model';


export const getPostApiAuthLoginResponseMock = (overrideResponse: Partial<Extract<LoginResponse, object>> = {}): LoginResponse => ({token: faker.string.alpha({length: {min: 10, max: 20}}), user: {id: faker.string.uuid(), email: faker.internet.email(), role: faker.helpers.arrayElement(Object.values(Role)), firstName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phone: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), teamId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), teamName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), rankingCount: faker.helpers.arrayElement([faker.number.int(), null]), active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])}, ...overrideResponse})

export const getPostApiAuthSetupPasswordResponseMock = (overrideResponse: Partial<Extract<PostApiAuthSetupPassword200, object>> = {}): PostApiAuthSetupPassword200 => ({message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), user: faker.helpers.arrayElement([{id: faker.string.uuid(), email: faker.internet.email(), role: faker.helpers.arrayElement(Object.values(Role)), firstName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phone: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), teamId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), teamName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), rankingCount: faker.helpers.arrayElement([faker.number.int(), null]), active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])}, undefined]), ...overrideResponse})

export const getPostApiAuthForgotPasswordResponseMock = (overrideResponse: Partial<Extract<PostApiAuthForgotPassword200, object>> = {}): PostApiAuthForgotPassword200 => ({message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getPostApiAuthResetPasswordResponseMock = (overrideResponse: Partial<Extract<PostApiAuthResetPassword200, object>> = {}): PostApiAuthResetPassword200 => ({message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getGetApiAuthProfileResponseMock = (overrideResponse: Partial<Extract<GetApiAuthProfile200, object>> = {}): GetApiAuthProfile200 => ({data: faker.helpers.arrayElement([{id: faker.string.uuid(), email: faker.internet.email(), role: faker.helpers.arrayElement(Object.values(Role)), firstName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phone: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), teamId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), teamName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), rankingCount: faker.helpers.arrayElement([faker.number.int(), null]), active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])}, undefined]), ...overrideResponse})

