/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLogData } from './auditLogData';

export interface AuditLog {
  id: string;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  userEmail?: string | null;
  action: string;
  entity: string;
  entityId: string;
  /** @nullable */
  data?: AuditLogData;
  createdAt: string;
}
