/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export interface ClassificationRow {
  position: number;
  teamId: string;
  teamName: string;
  player1?: string;
  player2?: string;
  played: number;
  wins: number;
  losses: number;
  setsWon?: number;
  setsLost?: number;
  setsDiff?: number;
  gamesWon?: number;
  gamesLost?: number;
  gamesDiff?: number;
  pointsFor?: number;
  pointsAgainst?: number;
  pointsDiff?: number;
  totalPoints: number;
}
