/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export interface CreateRankingRequest {
  name: string;
  description?: string;
  startDate: string;
  endDate: string;
  regulation?: string;
  locationId?: string;
  levelId?: string;
  categoryId?: string;
  poster?: string;
  rankingConfig?: string;
}
