/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiIncidentsStatus } from './getApiIncidentsStatus';

export type GetApiIncidentsParams = {
/**
 * Filtrar por ID de partido
 */
matchId?: string;
/**
 * Filtrar por estado
 */
status?: GetApiIncidentsStatus;
};
