/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMatchesStatus } from './getApiMatchesStatus';

export type GetApiMatchesParams = {
/**
 * Filtrar por ID de ranking
 */
rankingId?: string;
/**
 * Filtrar por ID de equipo
 */
teamId?: string;
/**
 * Filtrar por estado del partido
 */
status?: GetApiMatchesStatus;
};
