/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { IncidentStatus } from './incidentStatus';

export interface Incident {
  id: string;
  matchId: string;
  reportedBy: string;
  /** @nullable */
  reportedByEmail?: string | null;
  reportedAt: string;
  description: string;
  status: IncidentStatus;
  /** @nullable */
  resolution?: string | null;
  /** @nullable */
  resolvedBy?: string | null;
  /** @nullable */
  resolvedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
}
