/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type LiveMatchSessionGameMode = typeof LiveMatchSessionGameMode[keyof typeof LiveMatchSessionGameMode] | null;


export const LiveMatchSessionGameMode = {
  GOLDEN_POINT: 'GOLDEN_POINT',
  ADVANTAGE: 'ADVANTAGE',
} as const;
