/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type LivePointPayloadTeam = typeof LivePointPayloadTeam[keyof typeof LivePointPayloadTeam];


export const LivePointPayloadTeam = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
