/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type LiveMatchSessionIsTiebreak = typeof LiveMatchSessionIsTiebreak[keyof typeof LiveMatchSessionIsTiebreak];


export const LiveMatchSessionIsTiebreak = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
