/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Modalidad de juego (Punto de Oro o Con Ventajas)
 */
export type PostApiMatchesIdLiveRequestBodyGameMode = typeof PostApiMatchesIdLiveRequestBodyGameMode[keyof typeof PostApiMatchesIdLiveRequestBodyGameMode];


export const PostApiMatchesIdLiveRequestBodyGameMode = {
  GOLDEN_POINT: 'GOLDEN_POINT',
  ADVANTAGE: 'ADVANTAGE',
} as const;
