/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMatchesIdLivePointBodyTeam } from './postApiMatchesIdLivePointBodyTeam';

export type PostApiMatchesIdLivePointBody = {
  /** 1 para Equipo 1, 2 para Equipo 2 */
  team: PostApiMatchesIdLivePointBodyTeam;
};
