/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * 1 para Equipo 1, 2 para Equipo 2
 */
export type PostApiMatchesIdLivePointBodyTeam = typeof PostApiMatchesIdLivePointBodyTeam[keyof typeof PostApiMatchesIdLivePointBodyTeam];


export const PostApiMatchesIdLivePointBodyTeam = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
