/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMatchesRankingRankingIdGenerateBody = {
  /**
     * Número de vueltas a disputar (1 = Ida, 2 = Ida y Vuelta, etc.)
     * @minimum 1
     * @maximum 10
     */
  rounds?: number;
  /**
     * Lista opcional de IDs de equipos. Si no se indica, se usan los equipos inscritos activos.
     * @minItems 4
     */
  teamIds?: string[];
};
