/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMatchesIdResultBody = {
  /** Fecha real en que se disputó el partido (YYYY-MM-DD) */
  matchDate: string;
  /**
     * Juegos ganados por Equipo 1 en Set 1
     * @minimum 0
     */
  set1TeamOne: number;
  /**
     * Juegos ganados por Equipo 2 en Set 1
     * @minimum 0
     */
  set1TeamTwo: number;
  /**
     * Juegos ganados por Equipo 1 en Set 2
     * @minimum 0
     */
  set2TeamOne: number;
  /**
     * Juegos ganados por Equipo 2 en Set 2
     * @minimum 0
     */
  set2TeamTwo: number;
  /**
     * Juegos ganados por Equipo 1 en Set 3 (Desempate si 1-1)
     * @nullable
     */
  set3TeamOne?: number | null;
  /**
     * Juegos ganados por Equipo 2 en Set 3 (Desempate si 1-1)
     * @nullable
     */
  set3TeamTwo?: number | null;
  /**
     * Sets ganados por Equipo 1 (calculados automáticamente si se omiten)
     * @minimum 0
     * @maximum 2
     */
  setsTeamOne?: number;
  /**
     * Sets ganados por Equipo 2 (calculados automáticamente si se omiten)
     * @minimum 0
     * @maximum 2
     */
  setsTeamTwo?: number;
};
