/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PostApiTeamsBody = {
  name: string;
  player1Name: string;
  player1Surname: string;
  player2Name: string;
  player2Surname: string;
  reserveName?: string;
  reserveSurname?: string;
  phone?: string;
  phone2?: string;
  /**
     * @minItems 1
     * @maxItems 2
     */
  emails: string[];
};
