/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PostApiLocationsBody = {
  name: string;
  description?: string;
  /** Dirección o calle y número */
  street?: string;
  /** Ciudad o municipio */
  city?: string;
  /** Código postal */
  postalCode?: string;
  /** Provincia o comunidad */
  state?: string;
  country?: string;
};
