/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiMatchesIdAdminOverrideBodyStatus } from './putApiMatchesIdAdminOverrideBodyStatus';

export type PutApiMatchesIdAdminOverrideBody = {
  matchDate?: string;
  set1TeamOne?: number;
  set1TeamTwo?: number;
  set2TeamOne?: number;
  set2TeamTwo?: number;
  /** @nullable */
  set3TeamOne?: number | null;
  /** @nullable */
  set3TeamTwo?: number | null;
  setsTeamOne?: number;
  setsTeamTwo?: number;
  status?: PutApiMatchesIdAdminOverrideBodyStatus;
  /** Motivo opcional de la resolución auditada */
  reason?: string;
};
