/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PutApiMatchesIdAdminOverrideBodyStatus = typeof PutApiMatchesIdAdminOverrideBodyStatus[keyof typeof PutApiMatchesIdAdminOverrideBodyStatus];


export const PutApiMatchesIdAdminOverrideBodyStatus = {
  CONFIRMED: 'CONFIRMED',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  PENDING_RESULT: 'PENDING_RESULT',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
} as const;
