/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PutApiUsersOrganizersIdBody = {
  email?: string;
  /** @minLength 6 */
  password?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  active?: boolean;
};
