/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export type PutApiLocationsIdBody = {
  name?: string;
  description?: string;
  street?: string;
  city?: string;
  postalCode?: string;
  state?: string;
  country?: string;
};
