/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export interface Ranking {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  startDate: string;
  endDate: string;
  /** @nullable */
  regulation?: string | null;
  active: boolean;
  /** @nullable */
  poster?: string | null;
  /** @nullable */
  rankingConfig?: string | null;
  /** @nullable */
  locationId?: string | null;
  /** @nullable */
  locationName?: string | null;
  /** @nullable */
  levelId?: string | null;
  /** @nullable */
  levelName?: string | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  creatorEmail?: string | null;
  /** @nullable */
  teamCount?: number | null;
  createdAt?: string;
  updatedAt?: string;
}
