/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */

export interface SubmitResultPayload {
  matchDate: string;
  set1TeamOne?: number;
  set1TeamTwo?: number;
  set2TeamOne?: number;
  set2TeamTwo?: number;
  /** @nullable */
  set3TeamOne?: number | null;
  /** @nullable */
  set3TeamTwo?: number | null;
  setsTeamOne?: number;
  setsTeamTwo?: number;
}
