/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { TeamEmail } from './teamEmail';

export interface Team {
  id: string;
  name: string;
  player1Name: string;
  player1Surname: string;
  player2Name: string;
  player2Surname: string;
  /** @nullable */
  reserveName?: string | null;
  /** @nullable */
  reserveSurname?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  phone2?: string | null;
  active: boolean;
  emails?: (TeamEmail | string)[];
  createdAt?: string;
  updatedAt?: string;
}
