/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { Role } from './role';

export interface User {
  id: string;
  email: string;
  role: Role;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  teamId?: string | null;
  /** @nullable */
  teamName?: string | null;
  /** @nullable */
  rankingCount?: number | null;
  active?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
