/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PostApiCategoriesBody,
  PutApiCategoriesIdBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class CategoriesService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar todas las categorías
 */
 getApiCategories<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiCategories<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiCategories<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiCategories<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/categories`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/categories`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/categories`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Crear una nueva categoría (solo ADMIN)
 */
 postApiCategories<TData = void>(postApiCategoriesBody: PostApiCategoriesBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiCategories<TData = void>(postApiCategoriesBody: PostApiCategoriesBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiCategories<TData = void>(postApiCategoriesBody: PostApiCategoriesBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiCategories<TData = void>(
    postApiCategoriesBody: PostApiCategoriesBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/categories`,
      postApiCategoriesBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/categories`,
      postApiCategoriesBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/categories`,
      postApiCategoriesBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener categoría por ID
 */
 getApiCategoriesId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiCategoriesId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiCategoriesId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiCategoriesId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Actualizar categoría (solo ADMIN)
 */
 putApiCategoriesId<TData = void>(id: string,
    putApiCategoriesIdBody: PutApiCategoriesIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiCategoriesId<TData = void>(id: string,
    putApiCategoriesIdBody: PutApiCategoriesIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiCategoriesId<TData = void>(id: string,
    putApiCategoriesIdBody: PutApiCategoriesIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiCategoriesId<TData = void>(
    id: string,
    putApiCategoriesIdBody: PutApiCategoriesIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/categories/${id}`,
      putApiCategoriesIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/categories/${id}`,
      putApiCategoriesIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/categories/${id}`,
      putApiCategoriesIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Eliminar categoría (solo ADMIN)
 */
 deleteApiCategoriesId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiCategoriesId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiCategoriesId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiCategoriesId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

