/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PatchApiUsersIdActiveBody,
  PostApiUsersOrganizersBody,
  PutApiUsersOrganizersIdBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class UsersService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar todos los usuarios del sistema (solo ADMIN)
 */
 getApiUsers<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsers<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsers<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsers<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/users`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/users`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/users`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Listar todos los organizadores y rankings a su cargo (solo ADMIN)
 */
 getApiUsersOrganizers<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsersOrganizers<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsersOrganizers<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsersOrganizers<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/users/organizers`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/users/organizers`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/users/organizers`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Crear un nuevo usuario ORGANIZER (solo ADMIN)
 */
 postApiUsersOrganizers<TData = void>(postApiUsersOrganizersBody: PostApiUsersOrganizersBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiUsersOrganizers<TData = void>(postApiUsersOrganizersBody: PostApiUsersOrganizersBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiUsersOrganizers<TData = void>(postApiUsersOrganizersBody: PostApiUsersOrganizersBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiUsersOrganizers<TData = void>(
    postApiUsersOrganizersBody: PostApiUsersOrganizersBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/users/organizers`,
      postApiUsersOrganizersBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/users/organizers`,
      postApiUsersOrganizersBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/users/organizers`,
      postApiUsersOrganizersBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Actualizar datos de un usuario ORGANIZER (solo ADMIN)
 */
 putApiUsersOrganizersId<TData = void>(id: string,
    putApiUsersOrganizersIdBody?: PutApiUsersOrganizersIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiUsersOrganizersId<TData = void>(id: string,
    putApiUsersOrganizersIdBody?: PutApiUsersOrganizersIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiUsersOrganizersId<TData = void>(id: string,
    putApiUsersOrganizersIdBody?: PutApiUsersOrganizersIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiUsersOrganizersId<TData = void>(
    id: string,
    putApiUsersOrganizersIdBody?: PutApiUsersOrganizersIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/users/organizers/${id}`,
      putApiUsersOrganizersIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/users/organizers/${id}`,
      putApiUsersOrganizersIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/users/organizers/${id}`,
      putApiUsersOrganizersIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Eliminar un usuario ORGANIZER (solo ADMIN)
 */
 deleteApiUsersOrganizersId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiUsersOrganizersId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiUsersOrganizersId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiUsersOrganizersId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/users/organizers/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/users/organizers/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/users/organizers/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener detalle de usuario por ID (solo ADMIN)
 */
 getApiUsersId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsersId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsersId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsersId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Activar o desactivar un usuario (solo ADMIN)
 */
 patchApiUsersIdActive<TData = void>(id: string,
    patchApiUsersIdActiveBody: PatchApiUsersIdActiveBody, options?: HttpClientBodyOptions): Observable<TData>;
 patchApiUsersIdActive<TData = void>(id: string,
    patchApiUsersIdActiveBody: PatchApiUsersIdActiveBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 patchApiUsersIdActive<TData = void>(id: string,
    patchApiUsersIdActiveBody: PatchApiUsersIdActiveBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  patchApiUsersIdActive<TData = void>(
    id: string,
    patchApiUsersIdActiveBody: PatchApiUsersIdActiveBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/users/${id}/active`,
      patchApiUsersIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/users/${id}/active`,
      patchApiUsersIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/users/${id}/active`,
      patchApiUsersIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type GetApiUsersClientResult = NonNullable<void>
export type GetApiUsersOrganizersClientResult = NonNullable<void>
export type PostApiUsersOrganizersClientResult = NonNullable<void>
export type PutApiUsersOrganizersIdClientResult = NonNullable<void>
export type DeleteApiUsersOrganizersIdClientResult = NonNullable<void>
export type GetApiUsersIdClientResult = NonNullable<void>
export type PatchApiUsersIdActiveClientResult = NonNullable<void>
