/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  GetApiMatchesParams,
  PostApiMatchesIdDisputeBody,
  PostApiMatchesIdLiveAcceptBody,
  PostApiMatchesIdLivePointBody,
  PostApiMatchesIdLiveRequestBody,
  PostApiMatchesIdResultBody,
  PostApiMatchesRankingRankingIdGenerateBody,
  PutApiMatchesIdAdminOverrideBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              (item instanceof Date && !Number.isNaN(item.getTime()))),
        )
        .map((item) =>
          item instanceof Date ? item.toISOString() : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (value instanceof Date && !Number.isNaN(value.getTime())) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = value.toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class MatchesService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar partidos con filtros opcionales (rankingId, teamId, status)
 */
 getApiMatches<TData = void>(params?: GetApiMatchesParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiMatches<TData = void>(params?: GetApiMatchesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiMatches<TData = void>(params?: GetApiMatchesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiMatches<TData = void>(
    params?: GetApiMatchesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/matches`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/matches`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/matches`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * @summary Obtener detalle completo de un partido por ID
 */
 getApiMatchesId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiMatchesId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiMatchesId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiMatchesId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/matches/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/matches/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/matches/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Genera el fixture Round-Robin para los equipos inscritos en el ranking (mínimo 4). Permite configurar el número de vueltas (rounds). Preserva los partidos ya jugados entre equipos activos y elimina únicamente los partidos de equipos dados de baja y los partidos pendientes anteriores.
 * @summary Generar o regenerar calendario de partidos (ADMIN u ORGANIZER)
 */
 postApiMatchesRankingRankingIdGenerate<TData = void>(rankingId: string,
    postApiMatchesRankingRankingIdGenerateBody?: PostApiMatchesRankingRankingIdGenerateBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesRankingRankingIdGenerate<TData = void>(rankingId: string,
    postApiMatchesRankingRankingIdGenerateBody?: PostApiMatchesRankingRankingIdGenerateBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesRankingRankingIdGenerate<TData = void>(rankingId: string,
    postApiMatchesRankingRankingIdGenerateBody?: PostApiMatchesRankingRankingIdGenerateBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesRankingRankingIdGenerate<TData = void>(
    rankingId: string,
    postApiMatchesRankingRankingIdGenerateBody?: PostApiMatchesRankingRankingIdGenerateBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/ranking/${rankingId}/generate`,
      postApiMatchesRankingRankingIdGenerateBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/ranking/${rankingId}/generate`,
      postApiMatchesRankingRankingIdGenerateBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/ranking/${rankingId}/generate`,
      postApiMatchesRankingRankingIdGenerateBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Registrar resultado de un partido (Equipo participante)
 */
 postApiMatchesIdResult<TData = void>(id: string,
    postApiMatchesIdResultBody: PostApiMatchesIdResultBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdResult<TData = void>(id: string,
    postApiMatchesIdResultBody: PostApiMatchesIdResultBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdResult<TData = void>(id: string,
    postApiMatchesIdResultBody: PostApiMatchesIdResultBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdResult<TData = void>(
    id: string,
    postApiMatchesIdResultBody: PostApiMatchesIdResultBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/result`,
      postApiMatchesIdResultBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/result`,
      postApiMatchesIdResultBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/result`,
      postApiMatchesIdResultBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Confirmar resultado de un partido (Equipo rival)
 */
 postApiMatchesIdConfirm<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdConfirm<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdConfirm<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdConfirm<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/confirm`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/confirm`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/confirm`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Comunicar incidencia sobre un resultado (Equipo rival)
 */
 postApiMatchesIdDispute<TData = void>(id: string,
    postApiMatchesIdDisputeBody: PostApiMatchesIdDisputeBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdDispute<TData = void>(id: string,
    postApiMatchesIdDisputeBody: PostApiMatchesIdDisputeBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdDispute<TData = void>(id: string,
    postApiMatchesIdDisputeBody: PostApiMatchesIdDisputeBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdDispute<TData = void>(
    id: string,
    postApiMatchesIdDisputeBody: PostApiMatchesIdDisputeBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/dispute`,
      postApiMatchesIdDisputeBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/dispute`,
      postApiMatchesIdDisputeBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/dispute`,
      postApiMatchesIdDisputeBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Modificación administrativa de acta / resultado (solo ADMIN)
 */
 putApiMatchesIdAdminOverride<TData = void>(id: string,
    putApiMatchesIdAdminOverrideBody: PutApiMatchesIdAdminOverrideBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiMatchesIdAdminOverride<TData = void>(id: string,
    putApiMatchesIdAdminOverrideBody: PutApiMatchesIdAdminOverrideBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiMatchesIdAdminOverride<TData = void>(id: string,
    putApiMatchesIdAdminOverrideBody: PutApiMatchesIdAdminOverrideBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiMatchesIdAdminOverride<TData = void>(
    id: string,
    putApiMatchesIdAdminOverrideBody: PutApiMatchesIdAdminOverrideBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/matches/${id}/admin-override`,
      putApiMatchesIdAdminOverrideBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/matches/${id}/admin-override`,
      putApiMatchesIdAdminOverrideBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/matches/${id}/admin-override`,
      putApiMatchesIdAdminOverrideBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener listado de partidos actualmente en vivo o pendientes de aceptación
 */
 getApiMatchesLiveActive<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiMatchesLiveActive<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiMatchesLiveActive<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiMatchesLiveActive<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/matches/live/active`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/matches/live/active`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/matches/live/active`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Streaming Server-Sent Events (SSE) global para cambios en cualquier partido en vivo
 */
 getApiMatchesLiveStream<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiMatchesLiveStream<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiMatchesLiveStream<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiMatchesLiveStream<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/matches/live/stream`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/matches/live/stream`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/matches/live/stream`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener estado actual de la sesión en directo de un partido
 */
 getApiMatchesIdLive<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiMatchesIdLive<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiMatchesIdLive<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiMatchesIdLive<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/matches/${id}/live`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/matches/${id}/live`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/matches/${id}/live`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Conexión SSE para recibir actualizaciones en tiempo real del partido
 */
 getApiMatchesIdLiveStream<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiMatchesIdLiveStream<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiMatchesIdLiveStream<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiMatchesIdLiveStream<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/matches/${id}/live/stream`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/matches/${id}/live/stream`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/matches/${id}/live/stream`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Solicitar inicio de tanteo en directo en pista (Equipo participante o Admin)
 */
 postApiMatchesIdLiveRequest<TData = void>(id: string,
    postApiMatchesIdLiveRequestBody?: PostApiMatchesIdLiveRequestBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdLiveRequest<TData = void>(id: string,
    postApiMatchesIdLiveRequestBody?: PostApiMatchesIdLiveRequestBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdLiveRequest<TData = void>(id: string,
    postApiMatchesIdLiveRequestBody?: PostApiMatchesIdLiveRequestBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdLiveRequest<TData = void>(
    id: string,
    postApiMatchesIdLiveRequestBody?: PostApiMatchesIdLiveRequestBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/request`,
      postApiMatchesIdLiveRequestBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/request`,
      postApiMatchesIdLiveRequestBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/live/request`,
      postApiMatchesIdLiveRequestBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Aceptar invitación de partido en vivo en pista (Equipo rival o Admin)
 */
 postApiMatchesIdLiveAccept<TData = void>(id: string,
    postApiMatchesIdLiveAcceptBody?: PostApiMatchesIdLiveAcceptBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdLiveAccept<TData = void>(id: string,
    postApiMatchesIdLiveAcceptBody?: PostApiMatchesIdLiveAcceptBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdLiveAccept<TData = void>(id: string,
    postApiMatchesIdLiveAcceptBody?: PostApiMatchesIdLiveAcceptBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdLiveAccept<TData = void>(
    id: string,
    postApiMatchesIdLiveAcceptBody?: PostApiMatchesIdLiveAcceptBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/accept`,
      postApiMatchesIdLiveAcceptBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/accept`,
      postApiMatchesIdLiveAcceptBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/live/accept`,
      postApiMatchesIdLiveAcceptBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Anotar un punto para un equipo en tiempo real
 */
 postApiMatchesIdLivePoint<TData = void>(id: string,
    postApiMatchesIdLivePointBody: PostApiMatchesIdLivePointBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdLivePoint<TData = void>(id: string,
    postApiMatchesIdLivePointBody: PostApiMatchesIdLivePointBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdLivePoint<TData = void>(id: string,
    postApiMatchesIdLivePointBody: PostApiMatchesIdLivePointBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdLivePoint<TData = void>(
    id: string,
    postApiMatchesIdLivePointBody: PostApiMatchesIdLivePointBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/point`,
      postApiMatchesIdLivePointBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/point`,
      postApiMatchesIdLivePointBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/live/point`,
      postApiMatchesIdLivePointBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Deshacer el último punto anotado (Undo)
 */
 postApiMatchesIdLiveUndo<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdLiveUndo<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdLiveUndo<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdLiveUndo<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/undo`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/undo`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/live/undo`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Firma digital del acta oficial por el capitán de equipo
 */
 postApiMatchesIdLiveSign<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMatchesIdLiveSign<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMatchesIdLiveSign<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMatchesIdLiveSign<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/sign`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/matches/${id}/live/sign`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/matches/${id}/live/sign`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

