/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PostApiSponsorsBody,
  PutApiSponsorsIdBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class SponsorsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar todos los patrocinadores
 */
 getApiSponsors<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiSponsors<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSponsors<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSponsors<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/sponsors`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/sponsors`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/sponsors`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Crear un nuevo patrocinador (solo ADMIN)
 */
 postApiSponsors<TData = void>(postApiSponsorsBody: PostApiSponsorsBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSponsors<TData = void>(postApiSponsorsBody: PostApiSponsorsBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSponsors<TData = void>(postApiSponsorsBody: PostApiSponsorsBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSponsors<TData = void>(
    postApiSponsorsBody: PostApiSponsorsBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/sponsors`,
      postApiSponsorsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/sponsors`,
      postApiSponsorsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/sponsors`,
      postApiSponsorsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener patrocinador por ID
 */
 getApiSponsorsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSponsorsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSponsorsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSponsorsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/sponsors/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/sponsors/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/sponsors/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Actualizar patrocinador (solo ADMIN)
 */
 putApiSponsorsId<TData = void>(id: string,
    putApiSponsorsIdBody: PutApiSponsorsIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiSponsorsId<TData = void>(id: string,
    putApiSponsorsIdBody: PutApiSponsorsIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiSponsorsId<TData = void>(id: string,
    putApiSponsorsIdBody: PutApiSponsorsIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiSponsorsId<TData = void>(
    id: string,
    putApiSponsorsIdBody: PutApiSponsorsIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/sponsors/${id}`,
      putApiSponsorsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/sponsors/${id}`,
      putApiSponsorsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/sponsors/${id}`,
      putApiSponsorsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Eliminar patrocinador (solo ADMIN)
 */
 deleteApiSponsorsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiSponsorsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiSponsorsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiSponsorsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/sponsors/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/sponsors/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/sponsors/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

