/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PostApiLevelsBody,
  PutApiLevelsIdBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class LevelsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar todos los niveles
 */
 getApiLevels<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiLevels<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiLevels<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiLevels<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/levels`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/levels`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/levels`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Crear un nuevo nivel (solo ADMIN)
 */
 postApiLevels<TData = void>(postApiLevelsBody: PostApiLevelsBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLevels<TData = void>(postApiLevelsBody: PostApiLevelsBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLevels<TData = void>(postApiLevelsBody: PostApiLevelsBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLevels<TData = void>(
    postApiLevelsBody: PostApiLevelsBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/levels`,
      postApiLevelsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/levels`,
      postApiLevelsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/levels`,
      postApiLevelsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener nivel por ID
 */
 getApiLevelsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiLevelsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiLevelsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiLevelsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/levels/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/levels/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/levels/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Actualizar nivel (solo ADMIN)
 */
 putApiLevelsId<TData = void>(id: string,
    putApiLevelsIdBody: PutApiLevelsIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiLevelsId<TData = void>(id: string,
    putApiLevelsIdBody: PutApiLevelsIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiLevelsId<TData = void>(id: string,
    putApiLevelsIdBody: PutApiLevelsIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiLevelsId<TData = void>(
    id: string,
    putApiLevelsIdBody: PutApiLevelsIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/levels/${id}`,
      putApiLevelsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/levels/${id}`,
      putApiLevelsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/levels/${id}`,
      putApiLevelsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Eliminar nivel (solo ADMIN)
 */
 deleteApiLevelsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiLevelsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiLevelsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiLevelsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/levels/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/levels/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/levels/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

