/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PatchApiRankingsIdActiveBody,
  PostApiRankingsBody,
  PutApiRankingsIdBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class RankingsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar todos los rankings (público / admin)
 */
 getApiRankings<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiRankings<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiRankings<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiRankings<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/rankings`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/rankings`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/rankings`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Crear un nuevo ranking (ADMIN u ORGANIZER)
 */
 postApiRankings<TData = void>(postApiRankingsBody: PostApiRankingsBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiRankings<TData = void>(postApiRankingsBody: PostApiRankingsBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiRankings<TData = void>(postApiRankingsBody: PostApiRankingsBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiRankings<TData = void>(
    postApiRankingsBody: PostApiRankingsBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/rankings`,
      postApiRankingsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/rankings`,
      postApiRankingsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/rankings`,
      postApiRankingsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener detalle completo de un ranking
 */
 getApiRankingsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiRankingsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiRankingsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiRankingsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/rankings/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/rankings/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/rankings/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Actualizar datos de un ranking (ADMIN u ORGANIZER propietario)
 */
 putApiRankingsId<TData = void>(id: string,
    putApiRankingsIdBody: PutApiRankingsIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiRankingsId<TData = void>(id: string,
    putApiRankingsIdBody: PutApiRankingsIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiRankingsId<TData = void>(id: string,
    putApiRankingsIdBody: PutApiRankingsIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiRankingsId<TData = void>(
    id: string,
    putApiRankingsIdBody: PutApiRankingsIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/rankings/${id}`,
      putApiRankingsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/rankings/${id}`,
      putApiRankingsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/rankings/${id}`,
      putApiRankingsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Eliminar un ranking (ADMIN u ORGANIZER propietario)
 */
 deleteApiRankingsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiRankingsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiRankingsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiRankingsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/rankings/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/rankings/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/rankings/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Listar equipos inscritos en el ranking
 */
 getApiRankingsIdTeams<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiRankingsIdTeams<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiRankingsIdTeams<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiRankingsIdTeams<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/rankings/${id}/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/rankings/${id}/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/rankings/${id}/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Listar patrocinadores asociados al ranking
 */
 getApiRankingsIdSponsors<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiRankingsIdSponsors<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiRankingsIdSponsors<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiRankingsIdSponsors<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/rankings/${id}/sponsors`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/rankings/${id}/sponsors`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/rankings/${id}/sponsors`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Activar o pausar/desactivar un ranking (ADMIN u ORGANIZER propietario)
 */
 patchApiRankingsIdActive<TData = void>(id: string,
    patchApiRankingsIdActiveBody: PatchApiRankingsIdActiveBody, options?: HttpClientBodyOptions): Observable<TData>;
 patchApiRankingsIdActive<TData = void>(id: string,
    patchApiRankingsIdActiveBody: PatchApiRankingsIdActiveBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 patchApiRankingsIdActive<TData = void>(id: string,
    patchApiRankingsIdActiveBody: PatchApiRankingsIdActiveBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  patchApiRankingsIdActive<TData = void>(
    id: string,
    patchApiRankingsIdActiveBody: PatchApiRankingsIdActiveBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/rankings/${id}/active`,
      patchApiRankingsIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/rankings/${id}/active`,
      patchApiRankingsIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/rankings/${id}/active`,
      patchApiRankingsIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

