/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Padel Ranking API
 *
 * API REST para gestión de rankings de pádel.
 *
 * ## Autenticación
 * Usar JWT Bearer token. Obtener el token mediante POST /api/auth/login.
 *
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  PatchApiTeamsIdActiveBody,
  PostApiTeamsBody,
  PutApiTeamsIdBody
} from '../../model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class TeamsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Listar todos los equipos
 */
 getApiTeams<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiTeams<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiTeams<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiTeams<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/teams`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Crear un nuevo equipo (solo ADMIN)
 */
 postApiTeams<TData = void>(postApiTeamsBody: PostApiTeamsBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiTeams<TData = void>(postApiTeamsBody: PostApiTeamsBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiTeams<TData = void>(postApiTeamsBody: PostApiTeamsBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiTeams<TData = void>(
    postApiTeamsBody: PostApiTeamsBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/teams`,
      postApiTeamsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/teams`,
      postApiTeamsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/teams`,
      postApiTeamsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Obtener información detallada de un equipo
 */
 getApiTeamsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiTeamsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiTeamsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiTeamsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/teams/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/teams/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/teams/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Actualizar datos de un equipo (solo ADMIN)
 */
 putApiTeamsId<TData = void>(id: string,
    putApiTeamsIdBody: PutApiTeamsIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiTeamsId<TData = void>(id: string,
    putApiTeamsIdBody: PutApiTeamsIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiTeamsId<TData = void>(id: string,
    putApiTeamsIdBody: PutApiTeamsIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiTeamsId<TData = void>(
    id: string,
    putApiTeamsIdBody: PutApiTeamsIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/teams/${id}`,
      putApiTeamsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/teams/${id}`,
      putApiTeamsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/teams/${id}`,
      putApiTeamsIdBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Eliminar un equipo (ADMIN y ORGANIZER)
 */
 deleteApiTeamsId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiTeamsId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiTeamsId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiTeamsId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/teams/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/teams/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/teams/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Activar o desactivar un equipo (solo ADMIN)
 */
 patchApiTeamsIdActive<TData = void>(id: string,
    patchApiTeamsIdActiveBody: PatchApiTeamsIdActiveBody, options?: HttpClientBodyOptions): Observable<TData>;
 patchApiTeamsIdActive<TData = void>(id: string,
    patchApiTeamsIdActiveBody: PatchApiTeamsIdActiveBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 patchApiTeamsIdActive<TData = void>(id: string,
    patchApiTeamsIdActiveBody: PatchApiTeamsIdActiveBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  patchApiTeamsIdActive<TData = void>(
    id: string,
    patchApiTeamsIdActiveBody: PatchApiTeamsIdActiveBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/teams/${id}/active`,
      patchApiTeamsIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/teams/${id}/active`,
      patchApiTeamsIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/teams/${id}/active`,
      patchApiTeamsIdActiveBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Reenviar email de bienvenida / activación a los contactos del equipo (solo ADMIN)
 */
 postApiTeamsIdResendWelcome<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiTeamsIdResendWelcome<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiTeamsIdResendWelcome<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiTeamsIdResendWelcome<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/teams/${id}/resend-welcome`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/teams/${id}/resend-welcome`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/teams/${id}/resend-welcome`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

